# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
