# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170606_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(upload_to=b'account/static/img'),
        ),
    ]
