# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170606_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(upload_to=b'bookimages'),
        ),
    ]
