# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170606_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(upload_to=b'media/images/books'),
        ),
    ]
