# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170607_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ('science', 'Science'), ('romans', 'Romans')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
