# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
