# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170609_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
