# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2000)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hometown', models.CharField(max_length=100)),
                ('birthyear', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Musician'),
        ),
    ]
