# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='musician',
            new_name='author',
        ),
    ]
