# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170514_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='img_url',
            field=models.CharField(default='http://www.workyouenjoy.com/wp-content/uploads/2012/07/Red-Book.jpg', max_length=1000),
        ),
        migrations.AddField(
            model_name='books',
            name='pagenumbers',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='uitgever',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
